### ISSUE TITLE
Exception with final classes by doctrine

### ISSUE THREAD

**Issue by kaystrobach** [punktDe/oauth2-server#6]
```
neos/flow                               5.3.8                  Flow Application Framework
```

```
Unable to create a proxy for a final class "PunktDe\OAuth2\Server\Domain\Model\Client".
Type: Doctrine\Common\Proxy\Exception\InvalidArgumentException
  File:
Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/Exception/Inva
        lidArgumentException.php
  Line: 94

  Type: Neos\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
  Line: 718

```

Which version of flow have you been using?
